### ISSUE TITLE
List Index out of Range

### ISSUE THREAD

**Issue by tiredofit** [tristanlt/zabbix-rocketchat-stats#1]
Cool external script!
Trying to use with Python3 (with py3-openssl, py3-requests), have made edits to the URL, USER, PASS
yet receive the following error:

````bash
Traceback (most recent call last):
  File "rocketchat-stats-talk.py", line 87, in <module>
    statistics(url, user, password, sys.argv[1])
IndexError: list index out of range
````

**Comment by tristanlt** [comment]
Hi @tiredofit, thanks for your feedback. 
Did you try this script with zabbix or standalone ?
Did you have pass an argument ? It take one argument to get stat from rocket API.
Can you explain your environment ?
Regards,
Tristan

**Comment by tristanlt** [comment]
Can you try
```
python3 rocketchat-stats-talk.py activeUsers
```

**Comment by tiredofit** [comment]
Hi Tristanlt - 
Embearassingly, I had forgotten to put the argument at the end.
I'm seeing successs now!
I have modified the script to support multiple hostnames by inserting another argument as I monitor multiple rocketchat instances. This is great! Thank you.

**Comment by tristanlt** [comment]
Sound good @tiredofit 
Out of curiosity, is there part of Zabbix monitoring system ? 
Bye

**Comment by tiredofit** [comment]
Yes correct.
I made the following changes:

````bash
### Define RocketChat user !
host = sys.argv[1]
url = "https://" +host +"/api"
````
and changed the 

````bash
statistics(url, user, password, sys.argv[2])
````
In Zabbix. I modified the items to send a macro {$URL} before the API arguments.

**Comment by tristanlt** [comment]
Good, I hesitated between macro or script customization. I've choosen script customization for security concern but your use-case show me I've choosen the wrong way, macros are more versatiles.
I'll change this behavior ASAP
Thanks for your feedback
