### ISSUE TITLE
Does not work in CentOS7

### ISSUE THREAD

**Issue by BroadbandCommunicationsNorth** [tristanlt/zabbix-rocketchat-stats#2]
Tried to use this Script + Template  in CentOS7 (installed python3.4  and changed #!/usr/bin/python3) and got this error:
./rocketchat-stats  "onlineUsers"
Traceback (most recent call last):
  File "./rocketchat-stats", line 85, in <module>
    statistics(url, user, password, sys.argv[1])
  File "./rocketchat-stats", line 70, in statistics
    credentials = login(api_url, username, password)       
  File "./rocketchat-stats", line 54, in login
    if not "status" in r.json().keys():
  File "/usr/lib/python3.4/site-packages/requests/models.py", line 850, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib64/python3.4/site-packages/simplejson/__init__.py", line 516, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.4/site-packages/simplejson/decoder.py", line 374, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib64/python3.4/site-packages/simplejson/decoder.py", line 404, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.scanner.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by tristanlt** [comment]
Dear @BroadbandCommunicationsNorth 
can you tell me which RocketChat version is in use ? 
Can you reach https://rocket.chat.fqdn/api/v1/statistics ? 
It appear that login was OK but v1/statistics return something other than json.

Tristan

**Comment by tristanlt** [comment]
Hi @BroadbandCommunicationsNorth 
In example configuration, I've define an endpoint URL with RocketChat hosted inside a sub-uri (/chat). 
Perhaps this is not your case. 

Can you retry with rocketchat-stats from commit 11a9ac4f8c511c436026e47f08b7e201e85db459 ?
I've improving API communication errors management.

**Comment by BroadbandCommunicationsNorth** [comment]
> Dear @BroadbandCommunicationsNorth
> can you tell me which RocketChat version is in use ?
> Can you reach https://rocket.chat.fqdn/api/v1/statistics ?
> It appear that login was OK but v1/statistics return something other than json.
> 
> Tristan
Hi,
Thank you for quick reply.
Rocket chat version is  0.70.4
I can't reach https://rocket.chat.fqdn/api/v1/statistics
{"status":"error","message":"You must be logged in to do this."}, but I am.

**Comment by BroadbandCommunicationsNorth** [comment]
> Hi @BroadbandCommunicationsNorth
> In example configuration, I've define an endpoint URL with RocketChat hosted inside a sub-uri (/chat).
> Perhaps this is not your case.
> 
> Can you retry with rocketchat-stats from commit [11a9ac4](https://github.com/tristanlt/zabbix-rocketchat-stats/commit/11a9ac4f8c511c436026e47f08b7e201e85db459) ?
> I've improving API communication errors management.

It works! Thank you very much.

**Comment by tristanlt** [comment]
Thank you for your feedback
