### ISSUE TITLE
Error Test access on the commandline

### ISSUE THREAD

**Issue by halley1970** [tristanlt/zabbix-rocketchat-stats#8]
Hi,
I've got a Rocketchat server up and running.
Also in supervision, a Zabbix server (v4.4).

When I test the script, I get this error :
Do you have any idea. Thanking you for your answers.
Yours sincerely

******************************************************
Traceback (most recent call last):
  File "/usr/lib/zabbix/externalscripts/rocketchat-stats", line 100, in <module>
    statistics(url, headers, sys.argv[1])
  File "/usr/lib/zabbix/externalscripts/rocketchat-stats", line 86, in statistics
    pprint.pprint(data['statistics'])
KeyError: 'statistics'
******************************************************

**Comment by rmsmgaspar** [comment]
Hi,
I've the same issue, can you help us?
Thanks in advance

**Comment by tristanlt** [comment]
Hi, I'm pained that you have trouble using zabbix-rocketchat-stats

I've introduced a debug mode. (pease pull last commit)

Before running rocketchat-stats, please :
```
export ROCKETCHAT_STATS_DEBUG="True"
```
I'm interesting about debug informations 

Please could you tell me RocketChat version ? 

Regards,
Tristan

**Comment by rmsmgaspar** [comment]
Hi,
I'm with zabbix 4.4.6, this is the new version of the error:

Traceback (most recent call last):
  File "/usr/lib/zabbix/externalscripts/rocketchat-stats", line 105, in <module>
    statistics(url, headers, sys.argv[1])
  File "/usr/lib/zabbix/externalscripts/rocketchat-stats", line 92, in statistics
    pprint.pprint(data['statistics'])
KeyError: 'statistics'

Thanks

**Comment by halley1970** [comment]
Hi, 

RocketChat version => 3.0.4
export ROCKETCHAT_STATS_DEBUG="True" returns correctly DEBUG:root:RC API answers data

Which field do you want to check?
Regards,

**Comment by tristanlt** [comment]
Ok, I needs to test on a newer RocketChat (mine 2.2.0)
@halley1970 Could you send DEBUG message privately ? (needs to compare data structure with mine)
@rmsmgaspar  Have you retrieve today version of script ? 

Regard,
Tristan

**Comment by rmsmgaspar** [comment]
Yes, the error is different in lines.
My Rocket.Chat is 3.0.4

**Comment by halley1970** [comment]
Hi,

@halley1970 Could you send DEBUG message privately ?
Which email to send the 'DEBUG' file ?
Or how to post in MP ? (sorry I've never posted MPs on Github ... :( )
Yours sincerely,

**Comment by tristanlt** [comment]
Please mail me at tristan.letoullec@gmail.com

**Comment by tristanlt** [comment]
@halley1970,
Thanks you for debug informations. Seems like API answers directly a json with statistics instead of a json dict like ['statistics', 'success']. 
Haven't found anything on RocketChat changelog about statistics and API is versioned. I'm puzzled... 

Please could you :
```
curl -H "X-Auth-Token: 8h2mKAwxB3AQrFSjLVKMooJyjdCFaA7W45sWlHP8IzO" \
      -H "X-User-Id: ew28FnZqipDpvKw3R" \
      https://my.chat./api/v1/statistics
```
I'm interesting about answer structure.

(https://rocket.chat/docs/developer-guides/rest-api/miscellaneous/statistics/)

Regards,
Tristan

**Comment by buwzim** [comment]
Hi!

The JSON structure form the REST-Response was changed.
Old: 
{
  "statistics": {
    "_id":"wufRdmSrjmSMhBdTN",
	and so on
	
to New:
{
   "_id":"kvm3abnkDh6DP2SPT",
   and so on
   
Line 91 to 94 on externalscripts/rocketchat-stats:
    if statsname == "all":
        pprint.pprint(data['statistics'])
    elif statsname in data['statistics'].keys():
        print(data['statistics'][statsname])
		
needed an update for the new JSON Response

Keep up your good work

**Comment by scoopex** [comment]
Probably this might be fixed in https://github.com/tristanlt/zabbix-rocketchat-stats/pulls

**Comment by lennartgrunau** [comment]
I can confirm that the changes in #9 fixed the issue for me. Zabbix Version 5.0.1, rocketchat version 3.3.0.

**Comment by tristanlt** [comment]
Close by PR #9, thanks @scoopex
